---
- name: Add user list to the system
  user: 
    name: "{{ item.value.name }}"
    home: "/home/users/{{ item.value.name }}"
    createhome: no
    password: "{{ item.value.password }}"
    uid: "{{ item.value.uid }}"
    shell: /bin/bash
    update_password: on_create
    groups: "sudo"
  with_dict: "{{ users_dict }}"